# Manifold Sculpting

In [1]:
import matplotlib.pyplot as plt
import torch

In [73]:
k = 2
data = torch.Tensor([[1,1],[7,7],[9,9],[12,12], [5,5], [2,2]])
p = data[2]

data_size = torch.tensor(data.size())
m = data_dim[0] # number of data points
p_size = data_dim[1:] # size of the single datapoint
p_size0 = p_size - torch.ones_like(p_size) # to be used for indexing
print(p_size0)

tensor([1])


In [ ]:
def euclidean_dist(x,y):
    dist_sq = (x - y)*(x - y)
    return torch.sqrt(dist_sq)

In [59]:
# troviamo i 1i k vicini
scarti = p*torch.ones_like(data) - data
dist_sq = scarti*scarti
dist_sq = dist_sq.sum(dim=p_size_idx)

# sort the points
dist_sq, indices = torch.sort(dist_sq)
print(dist_sq)
# keep the first k (without the point itself)
kneighb = indices[1:k+1]
dist = torch.sqrt(dist_sq[1:k+1])

print(kneighb)
print(dist_sq[1:k+1])
print(dist)
# tutto qsto va in 1 ciclo sui .i

tensor([  0.,   8.,  18.,  32.,  98., 128.])
tensor([1, 3])
tensor([ 8., 18.])
tensor([2.8284, 4.2426])


In [89]:
x2 = data * data
x2 = x2.sum(axis=1)
# print(x2)
data_t = torch.transpose(data, 0, 1) # pb in dim >i (es foto...), credo funzioni cmq
xx = data@data_t
# print(xx)
# print(x2.unsqueeze(dim=1))
dist = torch.sqrt( x2 - 2*xx + x2.unsqueeze(dim=1) )
print(dist)

tensor([[ 0.0000,  8.4853, 11.3137, 15.5563,  5.6569,  1.4142],
        [ 8.4853,  0.0000,  2.8284,  7.0711,  2.8284,  7.0711],
        [11.3137,  2.8284,  0.0000,  4.2426,  5.6569,  9.8995],
        [15.5563,  7.0711,  4.2426,  0.0000,  9.8995, 14.1421],
        [ 5.6569,  2.8284,  5.6569,  9.8995,  0.0000,  4.2426],
        [ 1.4142,  7.0711,  9.8995, 14.1421,  4.2426,  0.0000]])


In [90]:
import numpy as np
data = np.array([[1,1],[7,7],[9,9],[12,12], [5,5], [2,2]])
x2 = np.sum(data*data,axis = 1)
print(x2)
print(x2.reshape((-1,1)))
data_t = np.copy(data.T)
#print(data_t)
xx = data@data_t
print("xx = \n",xx)
dist = np.sqrt(np.abs(x2.reshape((-1,1))-2*xx+x2))
# dist = np.abs(x2.reshape((-1,1))-2*xx+x2)

print("dist = \n", dist)

[  2  98 162 288  50   8]
[[  2]
 [ 98]
 [162]
 [288]
 [ 50]
 [  8]]
xx = 
 [[  2  14  18  24  10   4]
 [ 14  98 126 168  70  28]
 [ 18 126 162 216  90  36]
 [ 24 168 216 288 120  48]
 [ 10  70  90 120  50  20]
 [  4  28  36  48  20   8]]
dist = 
 [[ 0.          8.48528137 11.3137085  15.55634919  5.65685425  1.41421356]
 [ 8.48528137  0.          2.82842712  7.07106781  2.82842712  7.07106781]
 [11.3137085   2.82842712  0.          4.24264069  5.65685425  9.89949494]
 [15.55634919  7.07106781  4.24264069  0.          9.89949494 14.14213562]
 [ 5.65685425  2.82842712  5.65685425  9.89949494  0.          4.24264069]
 [ 1.41421356  7.07106781  9.89949494 14.14213562  4.24264069  0.        ]]
